=== tfreese/java/maven-proxy/src/main/resources/proxy-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:prox="http://github.com/tfreese/proxy-config"
           targetNamespace="http://github.com/tfreese/proxy-config"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
>

    <xs:element name="proxy-config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="port" type="xs:positiveInteger" />
                <xs:element name="repositories" type="prox:repositories" />
                <xs:element name="file-cache" type="prox:fileCache" minOccurs="0" />
                <xs:element name="db-monitoring" type="prox:dbMonitoring" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="httpUri">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="http:.*" />
            <xs:pattern value="https:.*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="repositories">
        <xs:sequence>
            <xs:element name="url" type="prox:httpUri" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fileCache">
        <xs:sequence>
            <xs:element name="enabled" type="xs:boolean" default="false" />
            <xs:element name="path" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dbMonitoring">
        <xs:sequence>
            <xs:element name="enabled" type="xs:boolean" default="true" />
            <xs:element name="jdbc-url" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== tfreese/java/maven-proxy/proxy-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://www.w3schools.com/xml/schema_intro.asp -->
<!-- xmlns:noNamespaceSchemaLocation="proxy-config.xsd" -->

<proxy-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://github.com/tfreese/maven-proxy/config"
              xsi:schemaLocation="http://github.com/tfreese/maven-proxy/config https://raw.githubusercontent.com/tfreese/java/master/maven-proxy/src/main/xsd/proxy-config.xsd">

    <port>7999</port>

    <repositories>
        <url>https://repo1.maven.org/maven2</url>
        <url>https://repo.spring.io/release</url>
        <url>https://repository.primefaces.org</url>
        <url>https://plugins.gradle.org/m2</url>
        <url>https://repo.gradle.org/gradle/libs-releases</url>
        <!--        <url>file:///home/tommy/.m2/repository</url>&lt;!&ndash; Just for testing &ndash;&gt;-->
    </repositories>

    <file-cache enabled="true">
        <local-url>file:///tmp/maven-proxy/cache</local-url>
        <create-directory>true</create-directory>
    </file-cache>

    <db-monitoring enabled="false">
        <jdbc-url>jdbc:string</jdbc-url>
    </db-monitoring>

</proxy-config>
